### ISSUE TITLE
Reconnect on disconnect

### ISSUE THREAD

**Issue by pironic** [WritheM/botPlug#23]
when the bot is disconnected from the websocket we need to reconnect. 

two reasons it could be disconnected:
- connected somewhere else
- maintenance

here is a screenshot of connected elsewhere: 
![image](https://cloud.githubusercontent.com/assets/541154/7977902/4ec77884-0a4c-11e5-822b-22afef88860e.png)

**Comment by pironic** [comment]
![image](https://cloud.githubusercontent.com/assets/541154/8049785/e9b5729c-0e20-11e5-9d0d-fc8445d8e0e6.png)
maintenance screen cap

**Comment by ylt** [comment]
Might take a little work to implement the disconnects cleanly - might be best to just throw in a try/catch for now and trigger a restart of itself. Will require changes to the bot core to allow for restarts.

**Comment by pironic** [comment]
agreed/understood. i'd like to implement a 2 min timeout and re-try to connect to the websocket when it dies for any reason.

**Comment by ylt** [comment]
Probably best to make it progressively longer, so that the first reconnect is instant, second is in 30 seconds, third is a minute, etc up to maybe 5 mins as the cap

**Comment by pironic** [comment]
we get a nice little warning too: 
![image](https://cloud.githubusercontent.com/assets/541154/8071844/379a9848-0ecb-11e5-8264-745e7bb07b02.png)

**Comment by pironic** [comment]
a reconnect and a new session see different errors. we'll need to handle both: 

![image](https://cloud.githubusercontent.com/assets/541154/8072045/e4ef7bf6-0ecd-11e5-93c0-34f22890109b.png)

**Comment by pironic** [comment]
arguably the batch file commit via c1f3c7a46b4be973cd3f634625c69d72c9693c4b was a fix for this, however we should still do this via the real code and not just restarting it when it crashes.

**Comment by ylt** [comment]
of course, but in its current state is probably still more stable than basicbot - think priority should be getting the basicbot feature-set across first

**Comment by pironic** [comment]
agreed. moved to 1.0. 

0.1 was a miss-click.

**Comment by ylt** [comment]
Going to be resolved as part of #44.
