### ISSUE TITLE
!lastSong Feature

### ISSUE THREAD

**Issue by Reanmachine** [WritheM/botPlug#24]
It would be really nice to mark yourself as playing your last song and have the bot remove you after the next song you play, I've on occasion loaded up a song or two and alt-tabbed to continue working.

After getting into the groove and completing the song I'm playing I forget I'm on deck (tunnel vision, called away, etc...) and i'll end up playing a song I don't mean to.

It usually isn't a problem as the lists I keep are mostly station friendly but it would be nice to have the bot cover me in case i'm not around to step out. (Leaving the list during a play = autoskip) :(

**Comment by pironic** [comment]
to build on this i was actually thinking something more like a !addfor commmand... maybe its something like

!addfor 3 @pironic in which case it auto removes me after i've played 3 songs. this would also be great for contest winners.

@reanmachine do you think this would solve your request?

**Comment by pironic** [comment]
will implement this as part of issue #27
