### ISSUE TITLE
Region Checking

### ISSUE THREAD

**Issue by pironic** [WritheM/botPlug#28]
If the currently playing song by any DJ is region locked for Canada, USA, France, or UK, then skip it.

**Comment by ylt** [comment]
Probably best to make it configurable, specify a list of the country codes in the config.json

API:
Can query the list method (first link) and specify the video id, returns a list of video entries (defined in link 2)
https://developers.google.com/youtube/v3/docs/videos/list
https://developers.google.com/youtube/v3/docs/videos

Probably could do additional checks based on the returned data such as the content rating
