### ISSUE TITLE
Link shortcuts

### ISSUE THREAD

**Issue by pironic** [WritheM/botPlug#3]
a list of commands that can be called on to provide a small blurb and a link. Could be kept in a json file for ease.

This will cover the need for the following commands:
- !autowoot
- !ba
- !commands
- !emoji
- !facebook
- !help
- !op
- !purchase
- !rcs
- !rules
- !theme
- !twitter
- !website
- !youtube

**Comment by ylt** [comment]
How are these being implemented? config based?
