### ISSUE TITLE
When the bot skips a song it should indicate WHY

### ISSUE THREAD

**Issue by Reanmachine** [WritheM/botPlug#31]
It'd be nice to know why the bot skipped a song randomly.

**Comment by ylt** [comment]
Yeah, random skips are a problem, but nothing to do with botplug - do intend to debug however

**Comment by Reanmachine** [comment]
Well at least if every botplug skip call requres a reason that's reported, then you can at least know what module it triggering. Or we'll know why.

**Comment by pironic** [comment]
its the auto advance feature of basicbot. i set to +5 seconds of the song, but i think i need to set more.

https://github.com/pironic/WritheM-plugdj-Bot/blob/master/extension.js#L337-342

**Comment by pironic** [comment]
I have removed the auto-skip feature of the basicBot. we can look at including a reasons field in the future for botPlug though.
