### ISSUE TITLE
!move command is misunderstood when target is the Radio Account

### ISSUE THREAD

**Issue by Reanmachine** [WritheM/botPlug#46]
Example:

```
Reanmachine @ 1:17pm
!move @WritheM Radio 4

WritheM Bot @ 1:17pm
[@Reanmachine] Not implemented yet

WritheM Radio @ 1:17pm
@Reanmachine, don't try to add me to the waitlist, please.
```

The intent was to move the bot to the bottom of the waitlist so we could get more resident dj / guest djs through since the waitlist was getting 20+ minutes. It seems to have gotten confused when i tried to move it.

**Comment by ylt** [comment]
Not an issue with Wallace, its an issue with BasicBot, it won't be a problem for Wallace once the feature is implemented however.
